# Generated by Django 4.1 on 2022-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title project', max_length=50)),
                ('description', models.TextField(help_text='Enter description project')),
                ('image', models.ImageField(upload_to='')),
                ('source', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
