# Generated by Django 4.1 on 2022-08-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(default=None, verbose_name='Полное описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default=None, verbose_name='Краткое описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(default=None, verbose_name='Дата и время добавления в портфолио'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(default=None, max_length=50, verbose_name='Ссылка на проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(default=None, max_length=50, verbose_name='Ссылка на исходный код'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Название проекта'),
        ),
    ]
