# Generated by Django 4.1 on 2022-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_description_project_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время добавления в портфолио'),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=50, verbose_name='Ссылка на проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(max_length=50, verbose_name='Ссылка на исходный код'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название проекта'),
        ),
    ]
